### ISSUE TITLE
Is it possible to support stylus?

### ISSUE THREAD

**Issue by alex-shamshurin** [mitermayer/vim-prettier#19]

**Comment by mitermayer** [comment]
Hi @alex-shamshurin thank you for raising this issue. 

vim-prettier is a wrapper on prettier and will support any parser that prettier supports. Unfortunately prettier at this stage has no support for stylus but feel free to raise an issue on https://github.com/prettier/prettier.

If the stylus support is then added to prettier we can then include the support on vim-prettier by following similar steps to this PR (https://github.com/mitermayer/vim-prettier/pull/17)

**Comment by mitermayer** [comment]
Will close this issue now, but feel free to re-open / submit a pull-request when prettier adds support for stylus. 

Thank you!
