### ISSUE TITLE
bump plugin dependency to prettier 1.5

### ISSUE THREAD

**Issue by mitermayer** [mitermayer/vim-prettier#22]
Prettier 1.5 has been release highlights are:

* GraphQL
* CSS-in-JS 
* JSON Support

We should be able now include JSON and GraphQL support

**Comment by andreiglingeanu** [comment]
Yeah, would love `json` filetype to be automatically detected too, it would be awesome!

**Comment by andreiglingeanu** [comment]
Detecting [`*.graphql` and `*.gql`](https://github.com/jparise/vim-graphql/blob/master/ftdetect/graphql.vim#L1) files would be enough, I think.

**Comment by mitermayer** [comment]
graphql support was added by https://github.com/mitermayer/vim-prettier/pull/17, and it should work fine as long as the user has filetype detection for the graphql filetype by some other plugins.

To avoid relying on other plugins for filetype detection I will be tracking it on https://github.com/mitermayer/vim-prettier/issues/23

**Comment by andreiglingeanu** [comment]
Makes a lot of sense. Thank you!

**Comment by mitermayer** [comment]
@andreiglingeanu  done :)
